name: Development Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'development/**'

permissions:
  contents: read

jobs:
  build-gradle-project:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get application version
        uses: thecodemonkey/action-get-gradle-version@master
        id: version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'



      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Change wrapper permissions
        run: powershell Set-ExecutionPolicy Unrestricted -Scope Process -Force; ./gradlew.bat

      - name: Make fat jar
        run: ./gradlew makeFatJar

      - name: Check jpackage availability
        run: |
          jpackage --input build\libs --name "Space Engineers Mod Manager" --main-jar Space-Engineers-Mod-Manager-${{ steps.getversion.outputs.version }}.jar --main-class com.gearshiftgaming.se_mod_manager.SpaceEngineersModManager --type app-image --app-version ${{ steps.getversion.outputs.version }} --icon "/src/main/resources/icons/logo.ico" --vendor "Gear Shift Gaming"

      - name: List contents of build/win directory
        run: dir build\win

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: SEMM-win
          draft: false
          prerelease: false

      - name: Upload .exe to release
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/win/SEMM-win.exe
          asset_name: SEMM-win.exe
          asset_content_type: application/exe