name: Development Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'development/**'

permissions:
  contents: read

jobs:
  build-gradle-project:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      - name: Read app version
        uses: kurt-code/gha-properties@v0.0.1
        id: read-properties
        with:
          operation: 'read'
          file-path: 'src/main/resources/version.properties'
          keys: 'version'
      - name: Save app version
        run: Add-Content -Path ${env:GITHUB_ENV} -Value "VERSION_INFORMATION=${{ steps.read-properties.outputs.version }}"

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Change wrapper permissions
        run: powershell Set-ExecutionPolicy Unrestricted -Scope Process -Force; ./gradlew.bat

      - name: Make fat jar
        run: ./gradlew makeFatJar

      - name: Check jpackage availability
        run: |
          jpackage --input build\libs --name "Space Engineers Mod Manager-v${{ env.VERSION_INFORMATION }}" --main-jar Space-Engineers-Mod-Manager-${{ env.VERSION_INFORMATION }}.jar --main-class com.gearshiftgaming.se_mod_manager.SpaceEngineersModManager --type app-image --app-version ${{ env.VERSION_INFORMATION }} --icon "src\main\resources\icons\logo.ico" --vendor "Gear Shift Gaming"

      - name: List contents of SEMM directory
        run: dir "Space Engineers Mod Manager-v${{ env.VERSION_INFORMATION }}"

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
            type: "zip"
            filename: "SEMM-v${{ env.VERSION_INFORMATION }}-win.zip"

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: SEMM-v${{ env.VERSION_INFORMATION }}-win
          tag: ${{ env.VERSION_INFORMATION }}

      - name: Upload archive to release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: "SEMM-v${{ env.VERSION_INFORMATION }}-win.zip"
            asset_name: "SEMM-v${{ env.VERSION_INFORMATION }}-win.zip"
            tag: ${{ env.VERSION_INFORMATION }}
            overwrite: true
            body: To use, extract the .zip folder to a directory and run the executable from there.