name: Release build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build-gradle-project:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      - name: Build with Gradle
        run: gradle build -x test

      - name: Read app version
        uses: kurt-code/gha-properties@v0.0.1
        id: read-properties
        with:
          operation: 'read'
          file-path: 'src/main/resources/version.properties'
          keys: 'version'
      - name: Save app version
        run: Add-Content -Path ${env:GITHUB_ENV} -Value "VERSION_INFORMATION=${{ steps.read-properties.outputs.version }}"

      - name: Change wrapper permissions
        run: powershell Set-ExecutionPolicy Unrestricted -Scope Process -Force; ./gradlew.bat

      - name: Make fat jar
        run: ./gradlew shadowJar

      - name: Remove unneeded browser binaries
        run: ./gradlew removeForeignOsBrowsers

      - name: Check jpackage availability
        run: |
          jpackage --input build\libs --name "Space Engineers Mod Manager-v${{ env.VERSION_INFORMATION }}" --main-jar Space-Engineers-Mod-Manager-${{ env.VERSION_INFORMATION }}.jar --main-class com.gearshiftgaming.se_mod_manager.SpaceEngineersModManager --type app-image --app-version ${{ env.VERSION_INFORMATION }} --icon "src\main\resources\icons\logo.ico" --vendor "Gear Shift Gaming"

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          directory: Space Engineers Mod Manager-v${{ env.VERSION_INFORMATION }}
          filename: "SEMM-v${{ env.VERSION_INFORMATION }}-win.zip"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_INFORMATION }}
          files: |
            Space Engineers Mod Manager-v${{ env.VERSION_INFORMATION }}/SEMM-v${{ env.VERSION_INFORMATION }}-win.zip
            build/libs/Space-Engineers-Mod-Manager-${{ env.VERSION_INFORMATION }}.jar
          body: "To use, extract the .zip folder to a directory and run the executable. Alternatively, you can download the .jar file and run standalone. You don't have to have Java installed for the .exe to run, but running the .jar will require Java21 and JavaFX.\n\n"
          generate_release_notes: true
          make_latest: true